force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/All_In_Price__c.field-meta.xml
<CustomField>
    <fullName>All_In_Price__c</fullName>
    <label>All In Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Configuration_Type__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Type__c</fullName>
    <label>Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Rehab</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Sale_Status__c</fullName>
    <label>Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Tenants Inventory</fullName>
            </value>
            <value>
                <fullName>Project Affected People</fullName>
            </value>
            <value>
                <fullName>Management Inventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_carpet_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Total_carpet_Sq_Ft__c</fullName>
    <label>Total carpet (Sq. Ft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Facing__c.field-meta.xml
<CustomField>
    <fullName>Unit_Facing__c</fullName>
    <label>Unit Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_InventoryMatrix.cls
public class Ex_InventoryMatrix {
    
    @AuraEnabled(cacheable=false)
    public static Opportunity getOppDetails(String oppId){
        try {
            Opportunity op = [SELECT Id, Name, Project__c, Project__r.Name, Project__r.Id FROM Opportunity WHERE Id = :oppId LIMIT 1];
            System.debug('op: ' + op);
            if (op != null && op.Project__c != null) {
                return op;
            } else {
                return null;
            }
        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled(cacheable=false)
    public static List<Project__c> getProjectList() {
        try {
            List<Project__c> pList = [SELECT Id, Name FROM Project__c];
            System.debug('Project List .: ' + pList);
            if (!pList.isEmpty()) {
                return pList;
            } else {
                return null;
            }
        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled
    public static List<Tower__c> getTower(String projId) {
        try {
            System.debug('Project Id: ' + projId);
            List<Tower__c> tList = [SELECT Id, Name, Project__c, Project__r.Name FROM Tower__c 
                                    WHERE Project__c = :projId];
            System.debug('Tower List .:' +tList);
            if (!tList.isEmpty()) {
                return tList;
            } else {
                return null;
            }
        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled
    public static List<Unit__c> getUnit(string towerId) {
        try {
            System.debug('Tower Id: ' + towerId);
            List<Unit__c> uList = [SELECT Name, Configuration_Type__c, Sale_Status__c, Opportunity__c FROM Unit__c 
                                   WHERE Tower__c = :towerId];
            System.debug('Unit List .:' +uList);
            if (uList != null && !uList.isEmpty()) {
                return uList;
            } else {
                return null;
            }
        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled
    public static Map<String, Integer> getUnitConfigurationMapDetails(String towerId){
        Map<String, Integer> unitConfigurationMap = new Map<String, Integer>();
        List<Unit__c> uList = [Select Id, Name, Floor__c, Sale_Status__c, Configuration_Type__c, 
                               Total_carpet_Sq_Ft__c, Purpose__c, Opportunity__c from Unit__c
                               where Configuration_Type__c != null 
                               AND Tower__c =: towerId  
                               ORDER BY Configuration_Type__c ASC, Name ASC];
        System.debug('Unit List .:' +uList);
        
        if(uList != null){
            for(Unit__c u : uList){
             
                if(!unitConfigurationMap.containsKey(u.Configuration_Type__c)){
                    unitConfigurationMap.put(u.Configuration_Type__c, 1);
                    System.debug('unitConfigurationMap if .: '+unitConfigurationMap);
                }else{
                    unitConfigurationMap.put(u.Configuration_Type__c, unitConfigurationMap.get(u.Configuration_Type__c) + 1);
                    System.debug('unitConfigurationMap else .: '+unitConfigurationMap);
                }
            }
        }
        System.debug('Unit Configuration Map .: '+unitConfigurationMap);
        if(unitConfigurationMap != null &&!unitConfigurationMap.isEmpty()){
            return unitConfigurationMap;
        }else{
            return null;
        }
    }
    
    @AuraEnabled
    public static Map<String, List<Unit__c>> getUnitFloorMapDetails(String towerId){
        Map<String, List<Unit__c>> unitFloorMap = new Map<String, List<Unit__c>>();
        List<Unit__c> uList = [Select Id, Name, Floor__c, Sale_Status__c, Configuration_Type__c, 
                               Total_carpet_Sq_Ft__c, Opportunity__c /*,Unit_Facing__c, All_In_Price__c*/ from Unit__c
                               where Tower__c =: towerId  ORDER BY Floor__c DESC, Name ASC];
        system.debug('uList: '+uList);
        
        if(uList != null){
            for(Unit__c u : uList){
               
                if(!unitFloorMap.containsKey('Floor: '+u.Floor__c)) {
                    List<Unit__c> newList = new List<Unit__c>();
                    newList.add(u);
                    unitFloorMap.put('Floor: '+u.Floor__c, newList);
                } else{
                      unitFloorMap.get('Floor: '+u.Floor__c).add(u);
                    }
            }
        }
        System.debug('unitFloorMap: '+unitFloorMap);
        if(unitFloorMap != null && !unitFloorMap.isEmpty()){
        return unitFloorMap;
        }else{
            return null;
        }
        
    }
 
}