force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/Bill_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bill_Stage__c</fullName>
    <label>Bill Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Actual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Name__c</fullName>
    <label>Charge Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental Charges</fullName>
            </value>
            <value>
                <fullName>Transport charges</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 1</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 2</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 3</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 4</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 5</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Misc/Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>Total_Amount__c - Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Draft_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Term_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term Sheet</label>
    <referenceTo>Term_Sheet__c</referenceTo>
    <relationshipName>Draft_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/Term_Sheet__c.object-meta.xml
<CustomObject>
    <label>Term Sheet</label>
    <nameField>
        <label>Term sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Sheet__c/fields/Brokerage_Interest__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Interest__c</fullName>
    <label>Brokerage Interest %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/fields/Corpus_Interest__c.field-meta.xml
<CustomField>
    <fullName>Corpus_Interest__c</fullName>
    <label>Corpus Interest %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/fields/MISC_Interest__c.field-meta.xml
<CustomField>
    <fullName>MISC_Interest__c</fullName>
    <label>MISC Interest %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/fields/Rent_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rent_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rent Interest %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/fields/Transport_Interest__c.field-meta.xml
<CustomField>
    <fullName>Transport_Interest__c</fullName>
    <label>Transport Interest %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Ex_BillInterestCalculatorBatch.cls
/*
    * Author        : Exceller Tech
    * Last Modified : 04/03/2025
    * Description   : Calculates the Interest for the Bills whose due date is passed until 
    *                 whole amount is paid (refering Remaining_Amount__c)
*/

public class Ex_BillInterestCalculatorBatch implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext batchableContext){
        
        return Database.getQueryLocator([ 
            SELECT Id, Name, Bill_Stage__c, Due_Date__c, Amount__c, Remaining__c, 
                   Charge_Name__c, Term_Sheet__r.Rent_Interest__c 
            FROM Bill__c 
            WHERE Bill_Stage__c = 'Actual' AND 
                  Term_Sheet__c != null AND 
                  Tenant__c != null AND 
                  Due_Date__c < :System.today() AND 
                  Amount__c != null AND 
                  Remaining__c > 0 
        ]);
    }


    public void execute(Database.BatchableContext batchableContext, List<Bill__c> bills){

        for (Bill__c bill : bills) {
            
            Decimal chargeAmount = bill.Amount__c;

            Date startDate = bill.Due_Date__c;
            Date endDate = System.today();
            Integer noOfDays = getDaysDifference(startDate, endDate);

            Decimal yearlyInterestPercentage = getYearlyInterestPercentage(bill);
            Decimal dailyInterestPercentage = yearlyInterestPercentage/365;

            Double totalInterest = (noOfDays*dailyInterestPercentage*chargeAmount)/100;
            bill.Interest_Amount__c = totalInterest;
        }

        if (bills != null && !bills.isEmpty()) {
            Database.update(bills);
        }
    }


    public void finish(Database.BatchableContext batchableContext){
        System.debug('Bill Interest Calculator Batch executed sucessfully !');
    }


    // Handle Scheduled Interest Bill Batch
    public void execute(System.SchedulableContext schedulableContext){
        Ex_BillInterestCalculatorBatch billInterestCalculator =  new Ex_BillInterestCalculatorBatch();
        Database.executeBatch(billInterestCalculator, 200);
    }


    // --- Utility Methods ---
    public static Integer getDaysDifference(Date startDate, Date endDate){
        return startDate.daysBetween(endDate);
    }


    // Returns 'Interest Percentage' for specified bill based on Bill Type
    // as we have charge wise Interest rates maintained on Term Sheet
    public static Decimal getYearlyInterestPercentage(Bill__c bill){

        String chargeName = bill.Charge_Name__c;

        if(chargeName == 'Rental Charges'){
            return bill.Term_Sheet__r.Rent_Interest__c;
        }
        if(chargeName == 'Transport charges'){
            return bill.Term_Sheet__r.Transport_Interest__c;
        }
        if(chargeName == 'Corpus Fund 1' || chargeName == 'Corpus Fund 2' || chargeName == 'Corpus Fund 3' ||
           chargeName == 'Corpus Fund 4' || chargeName == 'Corpus Fund 5'){
            return bill.Term_Sheet__r.Corpus_Interest__c;
        }
        if(chargeName == 'Brokerage'){
            return bill.Term_Sheet__r.Brokerage_Interest__c;
        }
        if(chargeName == 'Misc/Other'){
            return bill.Term_Sheet__r.MISC_Interest__c;
        }

        return null;
    }
}