force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Bill_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bill_Stage__c</fullName>
    <label>Bill Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Actual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Name__c</fullName>
    <label>Charge Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental Charges</fullName>
            </value>
            <value>
                <fullName>Transport charges</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 1</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 2</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 3</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 4</fullName>
            </value>
            <value>
                <fullName>Corpus Fund 5</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Misc/Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Draft_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Term_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term Sheet</label>
    <referenceTo>Term_Sheet__c</referenceTo>
    <relationshipName>Draft_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Sheet__c/Term_Sheet__c.object-meta.xml
<CustomObject>
    <label>Term Sheet</label>
    <nameField>
        <label>Term sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ex_DraftBillStageUpdateBatch.cls
public class Ex_DraftBillStageUpdateBatch implements Database.Batchable<sObject>, schedulable {
    
    public Database.queryLocator start(Database.BatchableContext bc){
        string query = 'SELECT Id, Name , Bill_Date__c,Amount__c, Charge_Name__c, Tenant__c, Term_Sheet__c, Bill_Stage__c, Due_Date__c '+
                       'FROM Bill__c Where Tenant__c !=null AND Bill_Date__c !=null AND Bill_Stage__c = \'Draft\' AND Amount__c !=null';
            
            return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc , List<Bill__c> draftBills){
        system.debug('draftBills '+draftBills);
        for(Bill__c db :draftBills){
            if(db.Bill_Date__c <= System.Today()){
                db.Bill_Stage__c = 'Actual';
            }
        }
        if(draftBills!=null  && draftBills.size()>0)
        Database.update(draftBills);
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
    
    public void execute(schedulableContext sc){
        Ex_DraftBillStageUpdateBatch dbStageUpdate = new Ex_DraftBillStageUpdateBatch();
        Database.executeBatch(dbStageUpdate,50);
    }
}