force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancellation In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Mobile__c</fullName>
    <label>Primary Applicant Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Title__c</fullName>
    <label>Primary Applicant Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/Construction_Stage__c.object-meta.xml
<CustomObject>
    <label>Construction Stage</label>
    <nameField>
        <label>Construction Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Construction Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Construction_Stage__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Tower__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Construction_Stage__c.field-meta.xml
<CustomField>
    <fullName>Construction_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Construction Stage</label>
    <referenceTo>Construction_Stage__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Construction_Stage_Description__c.field-meta.xml
<CustomField>
    <fullName>Construction_Stage_Description__c</fullName>
    <label>Construction Stage Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Deduct_Token__c.field-meta.xml
<CustomField>
    <fullName>Deduct_Token__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deduct Token</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Demand_Raised_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Raised_Date__c</fullName>
    <label>Demand Raised Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Is_Due__c.field-meta.xml
<CustomField>
    <fullName>Is_Due__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Due</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Is_Raised__c.field-meta.xml
<CustomField>
    <fullName>Is_Raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Milestone_Complete_At_Booking__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Complete_At_Booking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone Complete At Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Type__c</fullName>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date Linked</fullName>
            </value>
            <value>
                <fullName>Construction Linked</fullName>
            </value>
            <value>
                <fullName>Registration Linked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TDS_Threshold__c.field-meta.xml
<CustomField>
    <fullName>TDS_Threshold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TDS Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_DemandRaiseBatch.cls
/*-------------------------------------------
Project: Shraddha Lifespaces
Created By: Exceller Tech
Last Modified Date: 2023-10-04
//-------------------------------------------*/
global class Ex_DemandRaiseBatch implements Database.Batchable <sObject>, Database.Stateful, Schedulable {
    global String query;
    global Date cDate = system.today();
    global Booking__c bid;
    global Set<Id> pmIdSet = new Set<Id>(); 
    
    global Ex_DemandRaiseBatch() {
        String tempQuery = '';
        for (Integer i = 1; i <= 5; i++) {
            tempQuery += 'Charge_Bucket_' + i + '__c' + ',';
            tempQuery += 'Charge_Bucket_' + i + '_Amount__c' + ',';
            tempQuery += 'Charge_Bucket_' + i + '_Percentage__c' + ',';
            tempQuery += 'Charge_Bucket_' + i + '_CGST__c' + ',';
            tempQuery += 'Charge_Bucket_' + i + '_SGST__c' + ',';
            tempQuery += 'Charge_Bucket_' + i + '_Total_Tax__c' + ',';
        }
        
        //remove the last character only if its a comma.
        if (tempQuery.length() > 0 && tempQuery.substring(tempQuery.length() - 1).equals(','))   
            tempQuery = tempQuery.substring(0, tempQuery.length() - 1);
        query = 'SELECT Id, Name, Construction_Stage__c, Construction_Stage_Description__c, Deduct_Token__c, Demand_Raised_Date__c,'
            +' Due_Date__c, Is_Due__c, Is_Raised__c, Milestone_Complete_At_Booking__c, Milestone_Name__c, Milestone_Type__c, Is_Possession_Milestone__c,'
            +' Quotation__r.Booking__r.Primary_Applicant_Title__c, Quotation__r.Booking__r.Primary_Applicant_Name__c,'
            +' Quotation__r.Booking__r.Primary_Applicant_Mobile__c, Quotation__r.Booking__r.Primary_Applicant_Email__c,'
            +' Quotation__r.Booking__r.Project__r.Last_Demand_No__c, Quotation__r.Booking__r.Project__r.Starting_Demand_No__c,'
            +' Quotation__r.Booking__r.Project__r.Name,Quotation__r.Booking__r.Business_Region__c,Quotation__r.Booking__r.Project__r.TDS_Threshold__c,'
            +' Quotation__r.Booking__r.Project__r.Invoice_Number_Format__c,Quotation__r.Modified_Total_Other_Charges__c,Quotation__r.GST_On_Other_Charges__c,'
            +' Quotation__r.Booking__r.Agreement_Value__c,Number_of_Days__c, Quotation__c, Sequence_No__c, ' + tempQuery
            +' FROM Payment_Milestone__c'
            +' WHERE ((Milestone_Type__c = \'Date Linked\' AND Due_Date__c <= TODAY)'
            +' OR (Milestone_Type__c = \'Registration Linked\' AND Due_Date__c <= TODAY)'
            +' OR (Milestone_Type__c = \'Construction Linked\' AND Quotation__r.Booking__r.Registration_Status__c = \'Registration Completed\' AND Due_Date__c <= TODAY'
            +' AND Construction_Stage__r.Is_Completed__c = true) OR Is_Due__c = true)'
            +' AND Quotation__c != null'
            +' AND Quotation__r.Booking__c != null'
            +' AND Quotation__r.Unit__c != null'
            +' AND Quotation__r.Opportunity__r.Opportunity_Stage__c = \'Booked\''
            +' AND Quotation__r.Unit__r.Sales_Status__c = \'Booked\''
            +' AND Is_Raised__c = false'
            +' AND Quotation__r.Booking__r.Booking_Stage__c = \'Booking Confirmed\''
            +' ORDER BY Due_Date__c ASC';
        
        system.debug('query is :::: ' + query);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('query is :::: '+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<Payment_Milestone__c> pmList) {
        system.debug('pmList: '+pmList);
        for(Payment_Milestone__c pm: pmList) {
            system.debug('Milestone Id:' + pm.Id);
            Ex_DemandManagementServices.raiseDemand(pm);
            pmIdSet.add(pm.Id);
        }
    }
    
    global void finish(Database.BatchableContext info) {  
        system.debug('pmIdSet in finish: ' + pmIdSet);
        if (pmIdSet != null && !pmIdSet.isEmpty()) {
            // TODO : 
            // System.enqueueJob(new Ex_SendDemandLetterQueueable(pmIdSet));
        } else {
            system.debug('No demand IDs to process.');
        }   
    }   
    
    global void execute(SchedulableContext sc) {
        Ex_DemandRaiseBatch b = new Ex_DemandRaiseBatch(); 
        if (!Test.isRunningTest()){
            database.executebatch(b,1);
        }
    }
}