force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Mobile__c</fullName>
    <label>Primary Applicant Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Title__c</fullName>
    <label>Primary Applicant Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Demand_Status__c.field-meta.xml
<CustomField>
    <fullName>Demand_Status__c</fullName>
    <label>Demand Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Demand_Type__c.field-meta.xml
<CustomField>
    <fullName>Demand_Type__c</fullName>
    <label>Demand Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat Cost</fullName>
            </value>
            <value>
                <fullName>Debit Note</fullName>
            </value>
            <value>
                <fullName>Other Charge</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Other_Charges_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Other Charges Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Other_Charges_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges_Tax_Demanded__c</fullName>
    <label>Other Charges Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Payment_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Payment_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Milestone</label>
    <referenceTo>Payment_Milestone__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/TDS_Value_Demanded__c.field-meta.xml
<CustomField>
    <fullName>TDS_Value_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TDS Value Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Demanded__c</fullName>
    <label>Total Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Demand_Raised_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Raised_Date__c</fullName>
    <label>Demand Raised Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Is_Raised__c.field-meta.xml
<CustomField>
    <fullName>Is_Raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TDS_Percentage__c.field-meta.xml
<CustomField>
    <fullName>TDS_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Used to calculate TDS amount if Agreement Value crosses the TDS threshold amount.</description>
    <label>TDS Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TDS_Threshold__c.field-meta.xml
<CustomField>
    <fullName>TDS_Threshold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TDS Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Modified_Other_Charges__c.field-meta.xml
<CustomField>
    <fullName>Modified_Other_Charges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Modified Other Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Modified_Other_Charges_Tax__c.field-meta.xml
<CustomField>
    <fullName>Modified_Other_Charges_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Modified Other Charges Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/On_Account_Money__c.field-meta.xml
<CustomField>
    <fullName>On_Account_Money__c</fullName>
    <defaultValue>0</defaultValue>
    <label>On Account Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Ex_DemandManagementServices.cls
public class Ex_DemandManagementServices {
    public static void raiseDemand(Payment_Milestone__c pm) {
        if (pm != null) {
            try {
                // Step 1: Update Payment Milestone
                pm.Is_Raised__c = true;
                pm.Demand_Raised_Date__c = System.today();
                
                Decimal tdsPercentage = getTDSPercentage(pm.Quotation__r.Booking__r.Project__c);
                
                Decimal onAccountBalance = 0;
                onAccountBalance = getOnAccountBalance(pm.Quotation__r.Booking__c);
                system.debug('onAccountBalance: '+onAccountBalance);
                
                // Step 2: Create Demand Record
                Demand__c d = new Demand__c();
                d.Demand_Type__c = 'Flat Cost';
                d.Booking__c = pm.Quotation__r.Booking__c;
                d.Quotation__c = pm.Quotation__c;
                d.Payment_Milestone__c = pm.Id;
                d.Milestone_Name__c = pm.Milestone_Name__c;
                d.Invoice_Date__c = pm.Due_Date__c;
                d.Due_Date__c = pm.Due_Date__c.addDays(7); 
                d.Demand_Status__c = 'Raised';
                d.Customer_Name__c = pm.Quotation__r.Booking__r.Primary_Applicant_Title__c + ' ' + pm.Quotation__r.Booking__r.Primary_Applicant_Name__c;
                d.Customer_Mobile__c = pm.Quotation__r.Booking__r.Primary_Applicant_Mobile__c;
                d.Customer_Email__c = pm.Quotation__r.Booking__r.Primary_Applicant_Email__c;
                
                
                for (Integer i = 1; i <= 5; i++) {
                    if ((String) pm.get('Charge_Bucket_' + i + '__c') != null && String.isNotBlank((String) pm.get('Charge_Bucket_' + i + '__c'))) {
                        if (((String) pm.get('Charge_Bucket_' + i + '__c')).equalsIgnoreCase('Agreement Value')) {
                            if(pm.Quotation__r.Booking__r.Agreement_Value__c >= pm.Quotation__r.Booking__r.Project__r.TDS_Threshold__c) {
                                d.TDS_Value_Demanded__c = (((Decimal) pm.get('Charge_Bucket_' + i + '_Amount__c') / 100) * tdsPercentage).setScale(0,RoundingMode.HALF_UP);
                                d.Agreement_Value_Demanded__c = ((Decimal) pm.get('Charge_Bucket_' + i + '_Amount__c'));    /* As Per Client Requirement (- d.TDS_Value_Demanded__c);*/
                            } else {
                                d.Agreement_Value_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Amount__c');
                            }
                            d.Agreement_Value_Tax_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Total_Tax__c');
                            d.Total_Amount_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Amount__c');
                            d.Total_Tax_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Total_Tax__c');
                        } else if (((String) pm.get('Charge_Bucket_' + i + '__c')).equalsIgnoreCase('Other Charges')) {
                            d.Other_Charges_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Amount__c');
                            d.Other_Charges_Tax_Demanded__c = (Decimal) pm.get('Charge_Bucket_' + i + '_Total_Tax__c');
                        }
                    }
                }
                
                // TODO :
                // Step 2.1: Create Other Charges Demanded
                if (pm.Is_Possession_Milestone__c) {
                    if (pm.Quotation__r != null && pm.Quotation__r.Modified_Other_Charges__c != null) {
                        
                        try {
                            d.Other_Charges_Demanded__c = pm.Quotation__r.Modified_Other_Charges__c; // Amount without GST
                            d.Other_Charges_Tax_Demanded__c = pm.Quotation__r.Modified_Other_Charges_Tax__c; // Only GST amount
                        } catch (Exception ex) {
                            System.debug('Error: ' + ex.getMessage());
                        }
                    } else {
                        d.Other_Charges_Demanded__c = 0;
                        d.Other_Charges_Tax_Demanded__c = 0;
                    }
                }
                
                
                // Step 4: Insert Demand & Update PM
                Database.SaveResult insertResult = Database.insert(d, false);
                Database.SaveResult updateResult = Database.update(pm, false);
                
                // Step 4.1: Verify successful insert
                Set<Id> demandIdSet = new Set<Id>();
                if (!insertResult.isSuccess()) {
                    for (Database.Error error : insertResult.getErrors()) {
                        System.debug('Insert Error: ' + error.getMessage());
                    }
                }
                
                // Step 4.2: Verify successful update
                if (!updateResult.isSuccess()) {
                    for (Database.Error error : updateResult.getErrors()) {
                        System.debug('Update Error: ' + error.getMessage());
                    }
                }
                // Step 4: Handle On-Account Balance
                if (onAccountBalance > 0) {
                    Set<Id> rIdSet = getOnAccountBalanceReceipts(pm.Quotation__r.Booking__c);
                    if (rIdSet != null && !rIdSet.isEmpty()) {
                        // TODO : 
                        // Ex_ReceiptHandlerServices.receiptApporation(rIdSet);
                    }
                }
            } catch (Exception ex) {
                System.debug('Error: ' + ex.getMessage());
            }
        }
    }
    
    public static Decimal getOnAccountBalance(Id bId) {
        Decimal onAccountBalance = 0;
        List<Receipt__c> rList = [SELECT Id, Name, On_Account_Money__c FROM Receipt__c WHERE On_Account_Money__c > 0
                                  AND Booking__c = :bId ORDER BY Receipt_Date__c ASC];
        if(!rList.isEmpty() && rList != null){
            for (Receipt__c r : rList) {
                onAccountBalance += r.On_Account_Money__c;
            }
        }
        return onAccountBalance;
    }
    
    public static Set<Id> getOnAccountBalanceReceipts(Id bId) {
        Set<Id> rIdSet = new Set<Id>();
        List<Receipt__c> rList = [SELECT Id, Name, On_Account_Money__c FROM Receipt__c WHERE On_Account_Money__c > 0
                                  AND Booking__c = :bId ORDER BY Receipt_Date__c ASC];
        if(!rList.isEmpty() && rList != null){
            for (Receipt__c r : rList) {
                rIdSet.add(r.Id);
            }
        }
        return rIdSet;
    }
    

    // Returns the TDS percentage for the given project ID
    public static Decimal getTDSPercentage(Id pId) {
        
        Decimal tdsPercentage = 0;

        List<Project__c> pList = [SELECT Id, TDS_Percentage__c FROM Project__c WHERE Id = :pId];
        if (!pList.isEmpty()) {
            tdsPercentage = pList[0].TDS_Percentage__c;
        }

        return tdsPercentage;
    }
}