force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Checklist_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Booking_Checklist_Remarks__c</fullName>
    <label>Booking Checklist Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Checklist_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Checklist_Status__c</fullName>
    <label>Booking Checklist Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancellation In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Type__c.field-meta.xml
<CustomField>
    <fullName>Booking_Type__c</fullName>
    <label>Booking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quotation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Create_Booking_Verification_CheckList__c.field-meta.xml
<CustomField>
    <fullName>Create_Booking_Verification_CheckList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Booking Verification CheckList</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tenant_Account__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Verification_Checklist__c/Booking_Verification_Checklist__c.object-meta.xml
<CustomObject>
    <label>Booking Verification Checklist</label>
    <nameField>
        <label>Booking Verification Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Verification Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Verification_Checklist__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Verification_Checklist__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Verification Checklist</relationshipLabel>
    <relationshipName>Booking_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Verification_Checklist__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Verification_Checklist__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Verification_Checklist__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Booking_Verification_Checklist__c/Master_Booking_Verification_Checklist__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Master Booking Verification Checklist</label>
</CustomObject>

force-app/main/default/objects/Master_Booking_Verification_Checklist__c/fields/Required_Document_Task__c.field-meta.xml
<CustomField>
    <fullName>Required_Document_Task__c</fullName>
    <label>Required Document/Task</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tenant_Account__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Quotation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tenant Based</fullName>
    </customValue>
    <customValue>
        <fullName>Opportunity Based</fullName>
    </customValue>
    <masterLabel>Quotation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_BookingVerificationController.cls
public with sharing class Ex_BookingVerificationController {

    
    @AuraEnabled(cacheable=true)
   public static List<Booking__c> getBookings(String recordId){
       List<Booking__c> checkList = [select Id, Name,Create_Booking_Verification_CheckList__c, Booking_Date__c, Quotation__c,Booking_Type__c, Opportunity__c,
                                     Opportunity__r.Name,Tenant_Account__c,Tenant_Account__r.Name, Project__r.Name from Booking__c 
                                     where Id=:recordId];
       return checkList; 
   }
   
   
   @AuraEnabled(cacheable=true)
   public static List<Booking__c> checkCreateBookingVerificationCheckList(String recordId){
       List<Booking__c> checkList = [select Id,Create_Booking_Verification_CheckList__c, Booking_Date__c, Quotation__c,Booking_Type__c, Opportunity__c,
                                     Opportunity__r.Name,Tenant_Account__c,Tenant_Account__r.Name, Project__r.Name from Booking__c 
                                     where Id=:recordId AND Create_Booking_Verification_CheckList__c = False];
       return checkList; 
   }
   
   @AuraEnabled
   public static String changeGenarateCheckBoxValue(String recordId){ 
       try{
           List<Booking__c> bookList = [select Id,Create_Booking_Verification_CheckList__c from Booking__c where Id=:recordId]; 
           system.debug('booking is::'+bookList);
           for(Booking__c b:bookList){
               b.Id = b.Id;
               b.Create_Booking_Verification_CheckList__c = True;
               update b;
           }
           insertVerificationChecklist(bookList);
           return 'Generate Welcome Call Checklist Master changed to True';
       }catch(Exception e){
           System.debug('Exception:: '+e.getMessage());
           return e.getMessage();
       }
   }

   public static List<Booking_Verification_Checklist__c> insertVerificationChecklist(List<Booking__c> BookingList){
       List<Master_Booking_Verification_Checklist__c> welcomeCallMasterList = Master_Booking_Verification_Checklist__c.getall().values();
       List<Booking_Verification_Checklist__c> bookingVerificationChecklist = new List<Booking_Verification_Checklist__c>();
   
       if(BookingList != null && !BookingList.isEmpty()){
           for(Booking__c b:BookingList){
               for(Master_Booking_Verification_Checklist__c m:welcomeCallMasterList){
                   Booking_Verification_Checklist__c bvc = new Booking_Verification_Checklist__c();
                   bvc.Booking__c = b.Id;
                   bvc.Sequence_Number__c = m.Sequence_Number__c;
                   bvc.Category__c = m.Required_Document_Task__c;
                   bookingVerificationChecklist.add(bvc);
               }
           }
           if(!bookingVerificationChecklist.isEmpty() && bookingVerificationChecklist != null)
           insert bookingVerificationChecklist;
       }
       if(bookingVerificationChecklist != null && !bookingVerificationChecklist.isEmpty()){
           return bookingVerificationChecklist;
       }else {
           return null;
       }

   }

   @AuraEnabled
   public static List<Booking_Verification_Checklist__c> getBookingVerificationChecklistDetails(String bId) {
       try {
           List<Booking_Verification_Checklist__c> VerificationChecklistDetails = new List<Booking_Verification_Checklist__c>();
           VerificationChecklistDetails = [SELECT Id, Booking__c, Category__c, Values__c, Decision__c, Accepted__c,Sequence_Number__c FROM Booking_Verification_Checklist__c 
                                           WHERE Booking__c = :bId AND (Decision__c = '' OR Decision__c = 'Rejected') ORDER BY Sequence_Number__c ASC];
           return VerificationChecklistDetails;
       } catch (Exception e) {
           throw new AuraHandledException('Error retrieving Welcome Call Details: ' + e.getMessage());
       }
   }

   @AuraEnabled
   public static Id updateRecords(List<Booking_Verification_Checklist__c> records, List<Booking_Verification_Checklist__c> ConfirmedVerificationList, String bookId, String VerificationRemarks) {
       Decimal getRegistrationAmount = 0;
       Decimal getStampDutyAmount = 0;
       
       try {
           if (!records.isEmpty()){
               update records;
           }  
           if (!ConfirmedVerificationList.isEmpty()){
               update ConfirmedVerificationList;
           }
           
           List<Booking__c> bookingList = [
               SELECT Id, Quotation__c, Booking_Checklist_Status__c, Booking_Checklist_Remarks__c, Booking_Stage__c, Unit__c, Opportunity__c
               FROM Booking__c WHERE Id = :bookId
           ];
           
           if (bookingList.isEmpty()) {
               throw new AuraHandledException('No Booking record found for the provided ID.');
           }
           
           List<Booking_Verification_Checklist__c> welcomeList = [SELECT Id, Accepted__c FROM Booking_Verification_Checklist__c WHERE Booking__c = :bookId];
           
           boolean hasRejectedRecord = false; 
           for (Booking_Verification_Checklist__c bvc : welcomeList) {
               
               if(String.isNotBlank(VerificationRemarks)){
                bookingList[0].Booking_Checklist_Remarks__c = VerificationRemarks;    
               }
               if (bvc.Accepted__c == true) {
                   bookingList[0].Booking_Checklist_Status__c = 'Approved';
               } else {
                   hasRejectedRecord = true;
                   break;
               }
           }
           
           if (hasRejectedRecord) {
               bookingList[0].Booking_Checklist_Status__c = 'Rejected';
           }
           
           update bookingList[0];
           return bookId;
       } catch (Exception e) {
           throw new AuraHandledException('Error updating records: ' + e.getMessage());
       }
   }

}