force-app/main/default/objects/Blocking_Detail__c/Blocking_Detail__c.object-meta.xml
<CustomObject>
    <label>Blocking Detail</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Blocking Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blocking Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blocking_Detail__c/fields/Blocked_with_token__c.field-meta.xml
<CustomField>
    <fullName>Blocked_with_token__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked with token</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Blocked_without_token__c.field-meta.xml
<CustomField>
    <fullName>Blocked_without_token__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked without token</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Blocking_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Blocking_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocking Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blocking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Blocking Details</relationshipLabel>
    <relationshipName>Blocking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blocking_Detail__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Blocking Details</relationshipLabel>
    <relationshipName>Blocking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Last_Unit_Blocking_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Unit_Blocking_Date__c</fullName>
    <label>Last Unit Blocking Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Sale_Status__c</fullName>
    <label>Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Tenants Inventory</fullName>
            </value>
            <value>
                <fullName>Project Affected People</fullName>
            </value>
            <value>
                <fullName>Management Inventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_BlockingDetailsController.cls
public class Ex_BlockingDetailsController {
    @AuraEnabled(cacheable=true)
    public static Blocking_Detail__c getBlockDetails(string uniId){
        system.debug('uniId is::'+uniId);
        try {
            Blocking_Detail__c blockingDetailList = [select Id, Name, Status__c , Opportunity__c,Blocked_with_token__c, Blocked_without_token__c, Blocking_Comments__c , Amount__c,
                                                      Transaction_ID__c from Blocking_Detail__c where Unit__c =:  uniId AND Status__c ='Blocked' limit 1 ];
            
            system.debug('blockingDetailList:'+blockingDetailList);
            return blockingDetailList; 
        } catch(QueryException e) {
            System.debug('Exception is : ' + e.getMessage()); 
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Unit__c> fetchUnits(string uniId)
    {
        List<Unit__c> unitList = [select id, Name, Tower__r.Name , Project__r.Name ,Sale_Status__c,Last_Unit_Blocking_Date__c from Unit__c where Id =: uniId];
        if(unitList != null){
            return unitList; 
        }else{
            return null;
        }
        
    }
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOppName(string oppId){
        List<Opportunity> oppList = [SELECT Id , Name FROM Opportunity where Id =: oppId] ;
        if(oppList != null){
            return oppList; 
        }else{
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getModeOfFundingPicklist() {
        Map<String, List<String>> picklistValuesMap = new Map<String, List<String>>();
        Schema.DescribeFieldResult MOPFieldResult = Blocking_Detail__c.Mode_of_Payment__c.getDescribe();
        List<Schema.PicklistEntry> ModeOfFundingPicklistEntries = MOPFieldResult.getPicklistValues();
        List<String> ModeOfFundingPicklist = new List<String>();
        for (Schema.PicklistEntry entry : ModeOfFundingPicklistEntries) {
            ModeOfFundingPicklist.add(entry.getValue());
        }
        
        picklistValuesMap.put('Mode_of_Payment__c', ModeOfFundingPicklist);
        system.debug('picklistValuesMap ' +picklistValuesMap);
        return picklistValuesMap;
    }
    @AuraEnabled
    public static Blocking_Detail__c createBlockingRecord(Boolean blockByToken, Integer amount, String blockComment, String chequeNo, String unitName, string oppId ,string MOPpicklistValue)
    {
        Blocking_Detail__c blockInfo = new Blocking_Detail__c();
        blockInfo.Blocked_with_token__c = blockByToken;
        blockInfo.Amount__c = amount;
        blockInfo.Blocking_Comments__c = blockComment;
        blockInfo.Transaction_ID__c = chequeNo;
        blockInfo.Unit__c = unitName;
        blockInfo.Opportunity__c = oppId ;
        blockInfo.Blocking_Requested_By__c = UserInfo.getUserId();
        blockInfo.Mode_of_Payment__c = MOPpicklistValue ;
        try{
            insert blockInfo;
        }
        catch(exception ex)
        {
            throw new AuraHandledException(ex.getMessage());
        }
        blockInfo.Status__c = 'Blocked';
        update blockInfo;
        
        if (String.isNotBlank(unitName)) {
            Unit__c unit = [SELECT Id, Name, Sale_Status__c, Last_Unit_Blocking_Date__c FROM Unit__c WHERE Id = :unitName LIMIT 1];
            if (unit != null) {
                unit.Sale_Status__c = blockByToken ? 'Sale Hold with Money' : 'Sale Hold without Money';
                unit.Last_Unit_Blocking_Date__c = System.now();
                if (String.isNotBlank(oppId)) {
                    unit.Opportunity__c = oppId;  
                }
                update unit;
            }
        }
        return blockInfo;
    }

    @AuraEnabled
    public static Blocking_Detail__c unblockLogic(String blockId,String unblockComment)
    {
        Blocking_Detail__c unblock=[select id,Status__c,Unit__c from Blocking_Detail__c where id=:blockId AND Status__c ='Blocked' limit 1];
        Unit__c unit=[select id,Name,Sale_Status__c,Blocking_Comments__c from Unit__c where Id=:unblock.Unit__c];
        unblock.Status__c='Released';
        unit.Sale_Status__c='Vacant';
        unit.Blocking_Comments__c = unblockComment;
        unit.Opportunity__c = null ;
        update unit;
        update unblock;
        return unblock;
    }

}