force-app/main/default/objects/Society__c/Society__c.object-meta.xml
<CustomObject>
    <label>Society</label>
    <nameField>
        <label>Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Sheet__c/Term_Sheet__c.object-meta.xml
<CustomObject>
    <label>Term Sheet</label>
    <nameField>
        <label>Term sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Sheet__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Term Sheets</relationshipLabel>
    <relationshipName>Term_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_TermsheetTriggerHandler.cls
public class Ex_TermsheetTriggerHandler {
    
    public static void beforeInsert(List<Term_Sheet__c>termSheetList){
       Set<Id> societyIds = new Set<Id>();
        for(Term_Sheet__c termSheet :termSheetList ){
            if(termSheet.Society__c != null && termSheet.Start_Date__c != null && termSheet.End_Date__c != null )
                societyIds.add(termSheet.Society__c);
               
        }
        
        if(societyIds !=null && societyIds.size()>0)
          Ex_TermSheetHandlerService.TermSheetValidation(societyIds,termSheetList);
        
    }

}