force-app/main/default/objects/Escalation__c/Escalation__c.object-meta.xml
<CustomObject>
    <label>Escalation</label>
    <nameField>
        <displayFormat>ESC-{00000}</displayFormat>
        <label>Escallation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escalation__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Escalation</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Months</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Term_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term Sheet</label>
    <referenceTo>Term_Sheet__c</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Updated_Rent_Amount__c.field-meta.xml
<CustomField>
    <fullName>Updated_Rent_Amount__c</fullName>
    <label>Updated Rent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Society__c/Society__c.object-meta.xml
<CustomObject>
    <label>Society</label>
    <nameField>
        <label>Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Sheet__c/Term_Sheet__c.object-meta.xml
<CustomObject>
    <label>Term Sheet</label>
    <nameField>
        <label>Term sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Sheet__c/fields/Society__c.field-meta.xml
<CustomField>
    <fullName>Society__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Society</label>
    <referenceTo>Society__c</referenceTo>
    <relationshipLabel>Term Sheets</relationshipLabel>
    <relationshipName>Term_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Property_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_RentExcallationController.cls
public with sharing class Ex_RentExcallationController {
    public Ex_RentExcallationController() {
        
    }
    

    @AuraEnabled(cacheable=true)
    public static Term_Sheet__c getTermSheet(Id termSheetID){
        try {
            Term_Sheet__c termSheet = [SELECT Id, Name, Start_Date__c, End_Date__c
                                       FROM Term_Sheet__c
                                       WHERE Id = :termSheetID];
            return termSheet;
        } catch (Exception e) {
            throw new CustomException('Error occurred while retrieving Term sheet with specified ID : ' + termSheetID);
        }
    }

    @AuraEnabled
    public static string createEscallationRecords(List<Escalation__c> escalltionList, String tremSheetId, string propertyType){
        Integer startingHeap = Limits.getHeapSize();
        System.debug('startingHeap : ' + startingHeap);

        List<Escalation__c> escalltionListToInsert = new List<Escalation__c>();
        System.debug(' escalltionList '+escalltionList);
        System.debug(' tremSheetId '+ tremSheetId);
        System.debug(' propertyType '+ propertyType);

        Set<String> escallationHashes = getEscallationRecordsHash(tremSheetId);
        
        try{
            List<Term_Sheet__c> termSheet = [ Select id, Name, Society__c FROM Term_Sheet__c Where Id=: tremSheetId ];

            Ex_RentExcallationControllerBatch rentEscalationBatch = new Ex_RentExcallationControllerBatch(
                                                                            escalltionList,
                                                                            tremSheetId,
                                                                            propertyType,
                                                                            termSheet[0].Society__c
                                                                        );
            Database.executeBatch(rentEscalationBatch, 200);

            /*
            if(termSheet != null && termSheet.size() >0 && termSheet[0].Society__c != null){
                List<Account> tenantList = [Select id, Name, Rent_Amount__c, Society__c,Configuration__c, Property_Type__c FROM Account
                where RecordType.Name ='Tenant Account' AND Society__c =:termSheet[0].Society__c ];
                System.debug(' tenantList ' + tenantList);
                
              for(Account tenant : tenantList){
                    
                    for(Escalation__c es : escalltionList){

                        Date startDate = es.Start_Date__c;
                        Date endDate = es.End_Date__c;
                        String tenantID = tenant.Id;

                        String currentEscalationHash = getHash(startDate, endDate, tenantID);
                        if(escallationHashes.contains(currentEscalationHash)){
                            System.debug('Exisiting esclation found');
                            continue;
                        }

                        Escalation__c escalltion = new Escalation__c();
                        if(es.Start_Date__c != null)
                        escalltion.Start_Date__c = es.Start_Date__c;
                        if(es.End_Date__c != null)
                        escalltion.End_Date__c = es.End_Date__c;
                        if(es.Months__c != null)
                        escalltion.Months__c = es.Months__c;
                        if(es.Escalation__c != null)
                        escalltion.Escalation__c = es.Escalation__c;
                        if(es.Term_Sheet__c != null)
                        escalltion.Term_Sheet__c = es.Term_Sheet__c;
                        if(tenant.Society__c != null)
                        escalltion.Society__c = tenant.Society__c;
                        escalltion.Tenant__c = tenant.Id;
                        if(propertyType != null && propertyType != ''){
                            escalltion.Property_Type__c = propertyType;
                        }

                        // Updated Rent Amount
                        if(tenant.Rent_Amount__c != null && es.Escalation__c != null){
                            escalltion.Updated_Rent_Amount__c = tenant.Rent_Amount__c + (tenant.Rent_Amount__c*es.Escalation__c/100);
                        }

                         if(tenant.Configuration__c == null|| String.IsBlank(tenant.Configuration__c)  || tenant.Property_Type__c==null || String.IsBlank(Tenant.Property_Type__c)){
                            string msg = tenant.Name + ' does not have a maintained Configuration or Property Type ';
                            return msg;
                         }
                        
                        if(es.Configuration__c != null && es.Configuration__c.contains(tenant.Configuration__c) && tenant.Property_Type__c.equalsIgnoreCase(propertyType) ){
                             escalltion.Configuration__c = es.Configuration__c;
                            escalltionListToInsert.add(escalltion);
                        }
                          
                    }
                }
                system.debug('escalltionListToInsert'+escalltionListToInsert);
                if(escalltionListToInsert != null && escalltionListToInsert.size()>0)
                    insert escalltionListToInsert;
                
            }
            */
            
        }catch (exception e){
            return e.getMessage();
        }

        Integer endingHeap = Limits.getHeapSize();
        System.debug('startingHeap : ' + endingHeap);
        System.debug('endingHeap - startingHeap : ' + (endingHeap - startingHeap));

        return 'success';
    }


    // Create a set of Hashes for each Escalation, easy to compare two records
    public static Set<String> getEscallationRecordsHash(String termsSheetID){

        Set<String> escallationHashes = new Set<String>();
        List<Escalation__c> escallations = [SELECT Id, Name, Tenant__c, Start_Date__c, End_Date__c, Term_Sheet__c
                                            FROM Escalation__c
                                            WHERE Term_Sheet__c = :termsSheetID AND 
                                                Tenant__c != null AND
                                                Start_Date__c != null AND
                                                End_Date__c != null ];
        
        for (Escalation__c escallation : escallations) {
            String escallationHash = getHash(escallation.Start_Date__c, escallation.End_Date__c, escallation.Tenant__c);
            escallationHashes.add(escallationHash);
        }

        return escallationHashes;
    }

    // Generate as Unique value for Provided Data
    public static String getHash(Date startDate, Date endDate, String tenantId){
        
        String combinedInput = tenantId + startDate.format() + endDate.format();
        Blob inputBlob = Blob.valueOf(combinedInput);
        Blob hashBlob = Crypto.generateDigest('SHA-256', inputBlob);

        return EncodingUtil.convertToHex(hashBlob);
    }

    // ---- Custom Exception ----
    public class CustomException extends Exception {}

 
}